// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.hd123.sardine.wms.service.test.ia.user;

import com.hd123.sardine.wms.api.ia.user.RegisterUser;
import com.hd123.sardine.wms.api.ia.user.UserState;
import com.hd123.sardine.wms.common.utils.POJORandomInitionlizer;

public class RegisterUserBuilder extends RegisterUserBuilderBase<RegisterUserBuilder> {
    public static RegisterUserBuilder registerUser() {
        return new RegisterUserBuilder();
    }

    public RegisterUserBuilder() {
        super(new RegisterUser());
    }

    public RegisterUser build() {
        return getInstance();
    }
}

class RegisterUserBuilderBase<GeneratorT extends RegisterUserBuilderBase<GeneratorT>> {
    private RegisterUser instance;

    protected RegisterUserBuilderBase(RegisterUser aInstance) {
        instance = aInstance;
        POJORandomInitionlizer.randomInit(instance);
    }

    protected RegisterUser getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUuid(String aValue) {
        instance.setUuid(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCode(String aValue) {
        instance.setCode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPhone(String aValue) {
        instance.setPhone(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPasswd(String aValue) {
        instance.setPasswd(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUserState(UserState aValue) {
        instance.setUserState(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCompanyUuid(String aValue) {
        instance.setCompanyUuid(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCompanyCode(String aValue) {
        instance.setCompanyCode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCompanyName(String aValue) {
        instance.setCompanyName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAddress(String aValue) {
        instance.setAddress(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withHomePage(String aValue) {
        instance.setHomePage(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCompanyType(String aValue) {
        instance.setCompanyType(aValue);

        return (GeneratorT) this;
    }
}
