CREATE TABLE SARDINE_USER
(
  UUID           VARCHAR(32) NOT NULL,
  CODE           VARCHAR(30) NOT NULL,
  NAME           VARCHAR(100) NOT NULL,
  COMPANYUUID    VARCHAR(30) NOT NULL,
  COMPANYCODE    VARCHAR(30) NOT NULL,
  COMPANYNAME    VARCHAR(100) NOT NULL,
  PASSWD         VARCHAR(30) NOT NULL,
  PHONE          VARCHAR(30) NOT NULL,
  ADMINISTRATOR  VARCHAR(30) NOT NULL,
  CREATEDTIME    DATETIME NOT NULL,
  CREATEDID      VARCHAR(30) NOT NULL,
  CREATEDCODE    VARCHAR(30) NOT NULL,
  CREATEDNAME    VARCHAR(30) NOT NULL,
  LASTMODIFYTIME DATETIME NOT NULL,
  LASTMODIFYID   VARCHAR(30) NOT NULL,
  LASTMODIFYCODE VARCHAR(30) NOT NULL,
  LASTMODIFYNAME VARCHAR(30) NOT NULL,
  VERSION        NUMERIC(19) NOT NULL,
  USERSTATE      VARCHAR(30) NOT NULL
);

CREATE TABLE SARDINE_CUSTOMER
(
	UUID	       VARCHAR(32)	NOT NULL,
	CODE	       VARCHAR(30)	NOT NULL,
	NAME	       VARCHAR(100)	NOT NULL,
	CUSTOMERTYPE   VARCHAR(100)	NOT NULL,
	PHONE	       VARCHAR(100)	NOT NULL,
	ADDRESS	       VARCHAR(100)	NOT NULL,
	STATE		   VARCHAR(100)	NOT NULL,
	COMPANYUUID	   VARCHAR(30)	NOT NULL,
	REMARK	       VARCHAR(255)	NULL,
	VERSION	       INT	NOT NULL,
	CREATEDID	   VARCHAR(32)	NOT NULL,
	CREATEDCODE	   VARCHAR(30)	NOT NULL,
	CREATEDNAME	   VARCHAR(100)	NOT NULL,
	LASTMODIFYID   VARCHAR(32)	NOT NULL,
	LASTMODIFYCODE VARCHAR(30)	NOT NULL,
	LASTMODIFYNAME VARCHAR(100)	NOT NULL,
	CREATEDTIME	   DATETIME	NOT NULL,
	LASTMODIFYTIME DATETIME	NOT NULL
);