// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.hd123.sardine.wms.service.test.ia.role;

import java.util.Date;

import com.hd123.sardine.wms.api.ia.role.Role;
import com.hd123.sardine.wms.api.ia.role.RoleState;
import com.hd123.sardine.wms.common.entity.OperateInfo;
import com.hd123.sardine.wms.common.entity.Operator;
import com.hd123.sardine.wms.common.utils.POJORandomInitionlizer;

public class RoleBuilder extends RoleBuilderBase<RoleBuilder> {
    public static RoleBuilder role() {
        return new RoleBuilder();
    }

    public RoleBuilder() {
        super(new Role());
    }

    public Role build() {
        return getInstance();
    }
}

class RoleBuilderBase<GeneratorT extends RoleBuilderBase<GeneratorT>> {
    private Role instance;

    protected RoleBuilderBase(Role aInstance) {
        instance = aInstance;
        POJORandomInitionlizer.randomInit(instance);
    }

    protected Role getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCompanyUuid(String aValue) {
        instance.setCompanyUuid(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCode(String aValue) {
        instance.setCode(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withState(RoleState aValue) {
        instance.setState(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreateInfo(OperateInfo aValue) {
        instance.setCreateInfo(aValue);

        return (GeneratorT) this;
    }

    public CreateInfoOperateInfoBuilder withCreateInfo() {
        OperateInfo obj = new OperateInfo();

        withCreateInfo(obj);

        return new CreateInfoOperateInfoBuilder(obj);
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLastModifyInfo(OperateInfo aValue) {
        instance.setLastModifyInfo(aValue);

        return (GeneratorT) this;
    }

    public LastModifyInfoOperateInfoBuilder withLastModifyInfo() {
        OperateInfo obj = new OperateInfo();

        withLastModifyInfo(obj);

        return new LastModifyInfoOperateInfoBuilder(obj);
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withVersion(long aValue) throws UnsupportedOperationException {
        instance.setVersion(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUuid(String aValue) throws UnsupportedOperationException {
        instance.setUuid(aValue);

        return (GeneratorT) this;
    }

    public class CreateInfoOperateInfoBuilder
            extends OperateInfoBuilderBase<CreateInfoOperateInfoBuilder> {
        public CreateInfoOperateInfoBuilder(OperateInfo aInstance) {
            super(aInstance);
        }

        @SuppressWarnings("unchecked")
        public GeneratorT endCreateInfo() {
            return (GeneratorT) RoleBuilderBase.this;
        }
    }

    public class LastModifyInfoOperateInfoBuilder
            extends OperateInfoBuilderBase<LastModifyInfoOperateInfoBuilder> {
        public LastModifyInfoOperateInfoBuilder(OperateInfo aInstance) {
            super(aInstance);
        }

        @SuppressWarnings("unchecked")
        public GeneratorT endLastModifyInfo() {
            return (GeneratorT) RoleBuilderBase.this;
        }
    }

    public static class OperateInfoBuilderBase<GeneratorT extends OperateInfoBuilderBase<GeneratorT>> {
        private OperateInfo instance;

        protected OperateInfoBuilderBase(OperateInfo aInstance) {
            instance = aInstance;
        }

        protected OperateInfo getInstance() {
            return instance;
        }

        @SuppressWarnings("unchecked")
        public GeneratorT withTime(Date aValue) {
            instance.setTime(aValue);

            return (GeneratorT) this;
        }

        @SuppressWarnings("unchecked")
        public GeneratorT withOperator(Operator aValue) {
            instance.setOperator(aValue);

            return (GeneratorT) this;
        }

        public OperatorOperatorBuilder withOperator() {
            Operator obj = new Operator();

            withOperator(obj);

            return new OperatorOperatorBuilder(obj);
        }

        public class OperatorOperatorBuilder extends OperatorBuilderBase<OperatorOperatorBuilder> {
            public OperatorOperatorBuilder(Operator aInstance) {
                super(aInstance);
            }

            @SuppressWarnings("unchecked")
            public GeneratorT endOperator() {
                return (GeneratorT) OperateInfoBuilderBase.this;
            }
        }
    }

    public static class OperatorBuilderBase<GeneratorT extends OperatorBuilderBase<GeneratorT>> {
        private Operator instance;

        protected OperatorBuilderBase(Operator aInstance) {
            instance = aInstance;
        }

        protected Operator getInstance() {
            return instance;
        }

        @SuppressWarnings("unchecked")
        public GeneratorT withId(String aValue) {
            instance.setId(aValue);

            return (GeneratorT) this;
        }

        @SuppressWarnings("unchecked")
        public GeneratorT withCode(String aValue) {
            instance.setCode(aValue);

            return (GeneratorT) this;
        }

        @SuppressWarnings("unchecked")
        public GeneratorT withFullName(String aValue) {
            instance.setFullName(aValue);

            return (GeneratorT) this;
        }
    }
}
